name: Test 🧪

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: [main, develop] }

jobs:
  tests:
    name: ${{ matrix.suite }} ${{ matrix.icon }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - Units
          - PlayMode
        includes:
          - suite: Units
            icon: ✨
            testMode: editmode
          - suite: PlayMode
            icon: ▶
            testMode: playmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Test
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: testRunner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: ${{ matrix.testMode }}
      - uses: actions/upload-artifact@v2
        with:
          name: Test results (${{ matrix.suite }})
          path: ${{ steps.testRunner.outputs.artifactsPath }}
